### ISSUE TITLE
Error on startup : 'telegram_chatbot' object has no attribute 'selfid'

### ISSUE THREAD

**Issue by YashGovekar** [shashankbafna/cowin-vaccination-book-slot#2]
Hello, great app. 
I tried it once but after that it is throwing me error if I am trying it on another number. 
Can you please look into it?

`
###### Steps to subscribe ######

1) Open telegram app
2) Search for user (@CowinAutoBot) in the app
3) Send this message within 5 minutes from now: Subscribe 174188
Traceback (most recent call last):
  File "C:\Users\Yash\Downloads\cowin-vaccination-book-slot-main\src\cowinVaccinationSlotAutoBooking.py", line 6, in <module>
    from utils import generate_token_OTP, check_and_book, beep, BENEFICIARIES_URL, WARNING_BEEP_DURATION, \
  File "C:\Users\Yash\Downloads\cowin-vaccination-book-slot-main\src\utils.py", line 11, in <module>
    bot = telegram_chatbot(r"config.cfg")
  File "C:\Users\Yash\Downloads\cowin-vaccination-book-slot-main\src\telegramBot.py", line 15, in __init__
    self.selfid = self.read_selfid_from_config_file()
  File "C:\Users\Yash\Downloads\cowin-vaccination-book-slot-main\src\telegramBot.py", line 79, in read_selfid_from_config_file
    self.subscribe_To_Telegram()
  File "C:\Users\Yash\Downloads\cowin-vaccination-book-slot-main\src\telegramBot.py", line 60, in subscribe_To_Telegram
    self.selfid=self.recieveFromBot(timeout=300,isFirst=True,subsCap=f"Subscribe {captchSub}")
  File "C:\Users\Yash\Downloads\cowin-vaccination-book-slot-main\src\telegramBot.py", line 137, in recieveFromBot
    from_ = self.selfid
AttributeError: 'telegram_chatbot' object has no attribute 'selfid'`

**Comment by YashGovekar** [comment]
It started working again. Maybe some server issue. Thanks!

**Comment by shashankbafna** [comment]
Yes, it could be due to multiple updates happening on the same chatbot.
Currently this chatbot uses getUpdate method from telegram. This issue can be resolved once we find a URL through which we can use setwebhook method.

I am still trying to find a free hosting portal/website, which can source URL for this welfare activity. please let me know if you have a knowledge regarding this.
